### ISSUE TITLE
Loosen react in devDependencies

### ISSUE THREAD

**Issue by tomchentw** [timberio/react-facet-filter#3]
I've got this:

<img width="355" alt="screen shot 2016-08-24 at 10 51 37 am" src="https://cloud.githubusercontent.com/assets/922234/17916767/d7f13620-69e8-11e6-97ff-d97e9323ef8d.png">

Since my project is using:

``` json
"react": "15.0.1",
```

**Comment by tomchentw** [comment]
Also, `react-addons-css-transition-group` as well

**Comment by wuct** [comment]
Nice catch!

**Comment by zsherman** [comment]
@tomchentw could you give this a shot to make sure it doesn't break anything?
